server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://120.77.222.189:3306/code_fruit?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    # druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #Redis配置
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 47.99.57.148
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: 123
    #连接超时时间（ms）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0


#默认用户头像
default:
  user:
    avatar: 'http://plb0a02mt.bkt.clouddn.com/Fh1YDE2DSu6fmMfknDtkdR-t7QZ1'
    password: 123456